apiVersion: req.nephio.org/v1alpha1
kind: Interface
metadata:
  name: n2
  annotations:
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/owner: workload.nephio.org/v1alpha1.NFDeployment.oai-gnb
    specializer.nephio.org/namespace: oai-ran
spec:
  networkInstance:
    name: vpc-control
  cniType: macvlan
