# Interface for N3 (User Plane - gNB to UPF)
apiVersion: req.nephio.org/v1alpha1
kind: Interface
metadata:
  name: n3
  namespace: oai-ran
  annotations:
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/owner: req.nephio.org/v1alpha1.NFDeployment.gnb
  labels:
    nephio.org/interface: n3
    nephio.org/nf: gnb
    nephio.org/deployment-type: monolithic
spec:
  networkInstance:
    name: vpc-userplane
  cniType: macvlan
