# NetworkInstance for N2 control plane
apiVersion: infra.nephio.org/v1alpha1
kind: NetworkInstance
metadata:
  name: vpc-control
  namespace: oai-ran
  annotations:
    config.kubernetes.io/local-config: "true"
  labels:
    nephio.org/network: control
    nephio.org/nf-type: gnb
spec:
  name: vpc-control
  interfaces:
  - kind: bridgedomain
  - kind: interface
    selector:
      matchLabels:
        nephio.org/interface: n2
  pools:
  - name: n2-ipv4-pool
    prefixLength: 24
