# NetworkInstance for RU fronthaul
apiVersion: infra.nephio.org/v1alpha1
kind: NetworkInstance
metadata:
  name: vpc-fronthaul
  namespace: oai-ran
  annotations:
    config.kubernetes.io/local-config: "true"
  labels:
    nephio.org/network: fronthaul
    nephio.org/nf-type: gnb
spec:
  name: vpc-fronthaul
  interfaces:
  - kind: bridgedomain
  - kind: interface
    selector:
      matchLabels:
        nephio.org/interface: ru
  pools:
  - name: ru-ipv4-pool
    prefixLength: 24
