# Register oai-packages repo in Porch
# Apply to Management Cluster: kubectl apply -f oai-repo.yaml
apiVersion: config.porch.kpt.dev/v1alpha1
kind: Repository
metadata:
  name: oai-packages
  namespace: default
spec:
  type: git
  content: Package
  deployment: false
  git:
    repo: https://github.com/OPENAIRINTERFACE/oai-packages.git
    branch: r2
    directory: /
